export const ROUTES = {
  home: '/',
  programs: '/programs',
  programsCreate: '/programs/create',
  programDetail: (slug: string): string => `/programs/${slug}`,
  researchers: '/researchers',
  researcherDetail: (username: string): string => `/researchers/${username}`,
  companies: '/companies',
  companyDetail: (slug: string): string => `/companies/${slug}`,
  leaderboard: '/leaderboard',
  hallOfFame: '/hall-of-fame',
  blog: '/blog',
  blogPost: (slug: string): string => `/blog/${slug}`,
  help: '/help',
  faq: '/faq',
  about: '/about',
  disclosure: '/disclosure',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  security: '/security',
  search: '/search',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  authCallback: '/auth/callback',
  dashboard: '/dashboard',
  dashboardReports: '/dashboard/reports',
  dashboardReportNew: '/dashboard/reports/new',
  dashboardReport: (id: string): string => `/dashboard/reports/${id}`,
  dashboardWallet: '/dashboard/wallet',
  dashboardPayments: '/dashboard/payments',
  dashboardBadges: '/dashboard/badges',
  dashboardMessages: '/dashboard/messages',
  dashboardNotifications: '/dashboard/notifications',
  dashboardVerification: '/dashboard/verification',
  dashboardPrograms: '/dashboard/programs',
  dashboardSettings: '/dashboard/settings',
  company: '/company',
  companyOnboarding: '/company/onboarding',
  companyPrograms: '/company/programs',
  companyProgramNew: '/company/programs/new',
  companyProgramDetail: (id: string): string => `/company/programs/${id}`,
  companyReports: '/company/reports',
  companyReportDetail: (id: string): string => `/company/reports/${id}`,
  companyAnalytics: '/company/analytics',
  companyPayments: '/company/payments',
  companyMessages: '/company/messages',
  companyNotifications: '/company/notifications',
  companyResearchers: '/company/researchers',
  companySettings: '/company/settings',
  companyTeam: '/company/team',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminReports: '/admin/reports',
  adminPrograms: '/admin/programs',
  adminPayments: '/admin/payments',
  adminCompanies: '/admin/companies',
  adminDisputes: '/admin/disputes',
  adminModeration: '/admin/moderation',
  adminSupport: '/admin/support',
  adminVerification: '/admin/verification',
  adminAuditLogs: '/admin/audit-logs',
  adminSettings: '/admin/settings',
  profile: '/profile',
  settings: '/settings',
  welcome: '/welcome',
  appeal: '/appeal',
} as const;

export type RouteKey = keyof typeof ROUTES;

/** Static (non-function) routes only — useful for middleware matchers and sitemaps. */
export const STATIC_ROUTES: readonly string[] = [
  ROUTES.home,
  ROUTES.programs,
  ROUTES.programsCreate,
  ROUTES.researchers,
  ROUTES.companies,
  ROUTES.leaderboard,
  ROUTES.hallOfFame,
  ROUTES.blog,
  ROUTES.help,
  ROUTES.faq,
  ROUTES.about,
  ROUTES.disclosure,
  ROUTES.contact,
  ROUTES.privacy,
  ROUTES.terms,
  ROUTES.security,
  ROUTES.search,
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
  ROUTES.dashboard,
  ROUTES.dashboardReports,
  ROUTES.dashboardReportNew,
  ROUTES.dashboardWallet,
  ROUTES.dashboardPayments,
  ROUTES.dashboardBadges,
  ROUTES.dashboardMessages,
  ROUTES.dashboardNotifications,
  ROUTES.dashboardVerification,
  ROUTES.dashboardPrograms,
  ROUTES.dashboardSettings,
  ROUTES.company,
  ROUTES.companyOnboarding,
  ROUTES.companyPrograms,
  ROUTES.companyProgramNew,
  ROUTES.companyReports,
  ROUTES.companyAnalytics,
  ROUTES.companyPayments,
  ROUTES.companyMessages,
  ROUTES.companyNotifications,
  ROUTES.companyResearchers,
  ROUTES.companySettings,
  ROUTES.companyTeam,
  ROUTES.admin,
  ROUTES.adminUsers,
  ROUTES.adminReports,
  ROUTES.adminPrograms,
  ROUTES.adminPayments,
  ROUTES.adminCompanies,
  ROUTES.adminDisputes,
  ROUTES.adminModeration,
  ROUTES.adminSupport,
  ROUTES.adminVerification,
  ROUTES.adminAuditLogs,
  ROUTES.adminSettings,
  ROUTES.profile,
  ROUTES.settings,
  ROUTES.welcome,
  ROUTES.appeal,
] as const;

export function programUrl(slug: string): string {
  return ROUTES.programDetail(slug);
}

export function reportUrl(id: string): string {
  return ROUTES.dashboardReport(id);
}

export function companyProgramUrl(id: string): string {
  return ROUTES.companyProgramDetail(id);
}

export function companyReportUrl(id: string): string {
  return ROUTES.companyReportDetail(id);
}

export function companiesUrl(slug: string): string {
  return ROUTES.companyDetail(slug);
}
