export const ROUTES = {
  home: '/',
  programs: '/programs',
  programsCreate: '/programs/create',
  programDetail: (slug: string): string => `/programs/${slug}`,
  researchers: '/researchers',
  researcherDetail: (username: string): string => `/researchers/${username}`,
  companies: '/companies',
  leaderboard: '/leaderboard',
  hallOfFame: '/hall-of-fame',
  blog: '/blog',
  blogPost: (slug: string): string => `/blog/${slug}`,
  help: '/help',
  faq: '/faq',
  about: '/about',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  security: '/security',
  search: '/search',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  dashboard: '/dashboard',
  dashboardReports: '/dashboard/reports',
  dashboardReportNew: '/dashboard/reports/new',
  dashboardReport: (id: string): string => `/dashboard/reports/${id}`,
  dashboardWallet: '/dashboard/wallet',
  dashboardSettings: '/dashboard/settings',
  company: '/company',
  companyPrograms: '/company/programs',
  companyReports: '/company/reports',
  companySettings: '/company/settings',
  companyTeam: '/company/team',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminReports: '/admin/reports',
  adminPrograms: '/admin/programs',
  adminPayments: '/admin/payments',
  adminSettings: '/admin/settings',
  profile: '/profile',
  settings: '/settings',
  welcome: '/welcome',
  appeal: '/appeal',
  authCallback: '/auth/callback',
} as const;

export type RouteKey = keyof typeof ROUTES;

/** Static (non-function) routes only — useful for middleware matchers and sitemaps. */
export const STATIC_ROUTES: readonly string[] = [
  ROUTES.home,
  ROUTES.programs,
  ROUTES.programsCreate,
  ROUTES.researchers,
  ROUTES.companies,
  ROUTES.leaderboard,
  ROUTES.hallOfFame,
  ROUTES.blog,
  ROUTES.help,
  ROUTES.faq,
  ROUTES.about,
  ROUTES.contact,
  ROUTES.privacy,
  ROUTES.terms,
  ROUTES.security,
  ROUTES.search,
  ROUTES.login,
  ROUTES.register,
  ROUTES.forgotPassword,
  ROUTES.dashboard,
  ROUTES.dashboardReports,
  ROUTES.dashboardReportNew,
  ROUTES.dashboardWallet,
  ROUTES.dashboardSettings,
  ROUTES.company,
  ROUTES.companyPrograms,
  ROUTES.companyReports,
  ROUTES.companySettings,
  ROUTES.companyTeam,
  ROUTES.admin,
  ROUTES.adminUsers,
  ROUTES.adminReports,
  ROUTES.adminPrograms,
  ROUTES.adminPayments,
  ROUTES.adminSettings,
  ROUTES.profile,
  ROUTES.settings,
  ROUTES.welcome,
  ROUTES.appeal,
] as const;

export function programUrl(slug: string): string {
  return ROUTES.programDetail(slug);
}

export function reportUrl(id: string): string {
  return ROUTES.dashboardReport(id);
}
